--- 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gogs-data
  namespace: gogs  
  labels:
    appname: gogs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  
