kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gogs-postgres-data
  labels:
    appname: gogs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postregs.storageClass | quote }}
  resources:
    requests:
      storage: 1Gi
