kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    helm.sh/hook-weight: -2
  name: gogs-postgres-data
  labels:
    appname: gogs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.storageClass | quote }}
  resources:
    requests:
      storage: 1Gi
