--- 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gogs-data
  annotations:
    helm.sh/hook-weight: "-2"
    helm.sh/hook: pre-install    
  labels:
    appname: gogs
spec:
  accessModes:
    - {{ .Values.gogs.pvcMode | quote }}
  storageClassName: {{ .Values.gogs.storageClass | quote }}
  resources:
    requests:
      storage: 1Gi  
