kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-introspection
  namespace: gogs
subjects:
  - kind: ServiceAccount
    name: default
    namespace: gogs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: service-introspection
