kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-introspection
  namespace: gogs    
rules:
  - verbs:
      - list
      - watch
      - get
    apiGroups:
      - ''
    resources:
      - services
  - verbs:
      - list
      - watch
      - get
    apiGroups:
      - 'route.openshift.io'
    resources:
      - routes   
