kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-introspection
subjects:
  - kind: ServiceAccount
    name: default
    namespace: "{{ .Release.Namespace }}" 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: service-introspection
